chronic_medicare/urls.py
from django.conf.urls import patterns, url
from . import views 


urlpatterns = patterns('reports.views',
    url(r'^$', views.results_list, name='results_list'),
    url(r'^query/$', views.results_list, name='query'),
    url(r'^results/(?P<pk>[0-9]+)/$', views.results_detail, name='results_detail'),
)

mldjango/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from chronic_medicare import urls as chronic_urls


urlpatterns = [
    url(r'^$', 'chronic_medicare.views.home', name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^chronic-medicare/', include(chronic_urls, namespace="chronic")),
]

chronic_medicare/models.py
from django.db import models
from django.utils.encoding import python_2_unicode_compatible


@python_2_unicode_compatible
class AnalysisFile(models.Model):
    name = models.CharField(max_length=512)
    csv_file = models.FileField(upload_to='analysis-files/')
    description = models.TextField(max_length=1024, blank=True)

    class Meta:
      verbose_name_plural = "Raw Analysis Files"

    def __str__(self):
        return "{name}: {csv_file}".format(
            name=self.name,
            csv_file=self.csv_file.name.split('/')[-1])


@python_2_unicode_compatible
class ChronicConditionRegression(models.Model):
    source_file = models.ForeignKey(AnalysisFile, related_name="regressions")
    # NOTE: This is a very good case for either a FK, M2M, or ArrayField
    features = models.CharField(max_length=512)
    target = models.CharField(max_length=512)
    # NOTE: specify regression type, such as linear, logistic, etc. -- can this go wrong?
    analysis_type = models.CharField(max_length=512)
    description = models.TextField(max_length=2048, blank=True)
    summary_html = models.CharField(max_length=8192, blank=True)
    plot_html = models.CharField(max_length=8388608, blank=True)
    # Aikake's information criteria
    aic = models.FloatField(max_length=64, null=True, blank=True)
    # Bayes' information criteria
    bic = models.FloatField(max_length=64, null=True, blank=True)
    num_observations = models.IntegerField(null=True, blank=True)
    df_residuals = models.IntegerField(null=True, blank=True)
    r_squared = models.FloatField(max_length=64, null=True, blank=True)
    r_squared_adjusted = models.FloatField(max_length=64, null=True, blank=True)
    f_statistic = models.FloatField(max_length=64, null=True, blank=True)
    jarque_bera = models.FloatField(max_length=64, null=True, blank=True)
    jarque_bera_prob = models.FloatField(max_length=64, null=True, blank=True)
    skew = models.FloatField(max_length=64, null=True, blank=True)
    kurtosis = models.FloatField(max_length=64, null=True, blank=True)

    def __str__(self):
        return "{}: {} Regression from {}".format(
          self.id,
          self.analysis_type,
          self.source_file.name)

chronic_medicare/views.py
from django.shortcuts import render, get_object_or_404
from .models import ChronicConditionRegression


def home(request):
    return render(request, 'index.html')


def results_list(request):
    results = ChronicConditionRegression.objects.all()
    return render(request, 'chronic_medicare/results_list.html', {'results': results})

def results_detail(request, pk):
    result = get_object_or_404(ChronicConditionRegression, pk=pk)
    return render(request, 'chronic_medicare/results_detail.html', {'result': result})

templates/base.html
<html>  
    <head>
            <title>{% block title %}Machine Learning Workshop{% endblock title %}</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

            <script type="text/javascript" src="//code.jquery.com/jquery-2.1.4.min.js"></script>
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
        </head>
    <body>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
        <script type="text/javascript">
            {% block body_js %}
            {% endblock body_js %}
        </script>
    </body>
</html>

templates/chronic_medicare/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>Chronic Conditions Regressions</h1>
    <p>This tool allows you to explore and investigate data from <a href="https://www.cms.gov/research-statistics-data-and-systems/statistics-trends-and-reports/bsapufs/chronic_conditions_puf.html" target="ext">Centers for Medicare &amp; Medicaid Services</a>. We will be updating this project regularly so please visit again soon!</p>
{% endblock %}

templates/chronic_medicare/results_detail.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ result }}</h1>
    {{ result.plot_html|safe }}
    {{ result.summary_html|safe }}
    <p>R-Squared: {{ result.r_squared }}</p>
    <a href="{% url 'chronic:query' %}">Run new query</a>
    <a href="{% url 'chronic:results_list' %}">Return to list</a>
    <a href="{% url 'chronic:results_detail' result.pk|add:1 %}">See next result</a>
{% endblock %}

templates/chronic_medicare/results_list.html
{% extends 'base.html' %}

{% block content %}
    <h1>Chronic Condition Linear Regression Results</h1>
    <a href="{% url 'chronic:query' %}">Make new query</a>
    {% for result in results %}
        <h3>{{ result }}</h3>
        <p>Features: {{ result.features }}</p>
        <p>Target: {{ result.target }}</p>
        <p>R-Squared: {{ result.r_squared }}</p>
        <a href="{% url 'chronic:results_detail' result.pk  %}">Review results</a>
    {% endfor %}
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>Chronic Conditions Regressions</h1>
    <p>This tool allows you to explore and investigate data from <a href="https://www.cms.gov/research-statistics-data-and-systems/statistics-trends-and-reports/bsapufs/chronic_conditions_puf.html" target="ext">Centers for Medicare &amp; Medicaid Services</a>. We will be updating this project regularly so please visit again soon!</p>
{% endblock %}